# -*- coding: utf-8 -*-
"""Weather_info.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15EcSaVslIqcBDIRF7w3edcZ0r3xm-Afm
"""

from wwo_hist import retrieve_hist_data
import os
os.chdir('/content')
frequency = 3
start_date = '01-JUL-2020'
end_date = '31-JUL-2020'
api_key = 'a609919e2079435cb55154128201708'
location_list = ['Mumbai','Pune','Kolkata','Delhi','Chennai']
hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True)